file = inputText("Enter filename")
age = inputInteger("How old are you?")
message("You are %s years old" % (age,))
ok = question("Do you want to see config values of CUTE?")
if ok:
	clearOutput()
	output("auto indent: %d" % (autoIndent(),))
	output("backspace unindents: %d" % (backspaceUnindents(),))
	output("brace matching: %s" % (braceMatching(),))
	output("eol mode: %s" % (eolMode(),))
	output("eol visibility: %d" % (eolVisibility(),))
	output("folding: %d" % (folding(),))
	output("has selected text: %d" % (hasSelectedText(),))
	output("indentation guides: %d" % (indentationGuides(),))
	output("indentation uses tabs: %d" % (indentationsUseTabs(),))
	output("indentation width: %d" % (indentationWidth(),))
	output("modified: %d" % (isModified(),))
	output("read only: %d" % (isReadOnly(),))
	output("redo available: %d" % (isRedoAvailable(),))
	output("undo available: %d" % (isUndoAvailable(),))
	output("utf8: %d" % (isUtf8(),))
	output("lines: %d" % (lines(),))
	output("length: %d" % (length(),))
	output("tab indents: %d" % (tabIndents(),))
	output("tab width: %d" % (tabWidth(),))
	output("whitespace visibility: %d" % (whitespaceVisibility(),))
