#ifndef __PIXMAPS_H__
#define __PIXMAPS_H__

#include "build.xpm"
#include "close.xpm"
#include "compile.xpm"
#include "copy.xpm"
#include "cut.xpm"
#include "docin.xpm"
#include "findinfiles.xpm"
#include "findnext.xpm"
#include "forward.xpm"
#include "help.xpm"
#include "left.xpm"
#include "new.xpm"
#include "next.xpm"
#include "open.xpm"
#include "paste.xpm"
#include "prev.xpm"
#include "print.xpm"
#include "qtlogo.xpm"
#include "redo.xpm"
#include "replace.xpm"
#include "replace2.xpm"
#include "right.xpm"
#include "save.xpm"
#include "saveall.xpm"
#include "search.xpm"
#include "stop.xpm"
#include "undo.xpm"
#include "world.xpm"
#include "xbuild.xpm"
#include "ExecuteScript.xpm"
#include "FullScreen.xpm"
#include "SaveAs.xpm"

#endif
